name: 02 - Eventos
on: [push]
on: pull_request
on: schedule 40 16 14 11 4
on: workflow_dispatch
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: ShowTrigger
        run: |
             echo "${{ github.event_name }}"
  
