name: 02 - Eventos
on: 
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '50 16 14 11 4'
  
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: ShowTrigger
        run: |
             echo "${{ github.event_name }}"
  
