name: 02 - Eventos
on: push
    pull_request
    schedule 40 16 14 11 4
    workflow_dispatch
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: ShowTrigger
        run: |
             echo "${{ github.event_name }}"
  
